import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function HelpScreen() { const colors = useColors(); const router = useRouter(); return <ScreenContainer><ScrollView contentContainerStyle={styles.page}><View style={styles.nav}><MaterialIcons name="arrow-back" size={22} color={colors.foreground} onPress={() => router.back()} /><Text style={[styles.navTitle, { color: colors.foreground }]}>Aethel guide</Text><View style={{ width: 22 }} /></View><Text style={[styles.eyebrow, { color: colors.primary }]}>DOCUMENTATION</Text><Text style={[styles.title, { color: colors.foreground }]}>A calmer way to run the day.</Text><Text style={[styles.lead, { color: colors.muted }]}>A short guide to the product, what is protected, and what each area is for.</Text><Guide icon="vpn-key" title="Vault" body="Add passwords, cards, and private notes. Reveal and copy are guarded by biometrics on supported devices. New vault content is encrypted locally before optional sync." /><Guide icon="event-note" title="Bills" body="Track upcoming, overdue, and paid reminders. The dashboard surfaces urgency without turning every notification into an interruption." /><Guide icon="timer" title="Focus" body="Start a short focus block, pause it, or end it early. The current app provides the focus ritual; operating-system-level app blocking requires native entitlements and permission." /><Guide icon="cloud-sync" title="Sync" body="Google sign-in creates your account. Encrypted vault payloads and the records needed for continuity can sync to the SQL backend. Offline mode remains available." /><Guide icon="security" title="Security model" body="Firebase verifies identity. The server maps your Firebase UID to a SQL user row. Vault plaintext is not sent to the API; device keys stay in secure storage where supported." /><View style={[styles.note, { backgroundColor: colors.inkSoft }]}><Text style={[styles.noteTitle, { color: colors.foreground }]}>Need help?</Text><Text style={[styles.noteBody, { color: colors.muted }]}>Use the repository issue tracker for product questions or deletion requests. Never post a password, card number, recovery code, or vault secret.</Text></View></ScrollView></ScreenContainer>; }
function Guide({ icon, title, body }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; body: string }) { const colors = useColors(); return <View style={[styles.guide, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={[styles.icon, { backgroundColor: colors.inkSoft }]}><MaterialIcons name={icon} size={20} color={colors.primary} /></View><View style={styles.copy}><Text style={[styles.guideTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.guideBody, { color: colors.muted }]}>{body}</Text></View></View>; }
const styles = StyleSheet.create({ page: { padding: 22, paddingBottom: 42, gap: 13 }, nav: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }, navTitle: { fontSize: 16, fontWeight: "900" }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { fontSize: 32, lineHeight: 36, fontWeight: "900", letterSpacing: -1.2 }, lead: { fontSize: 16, lineHeight: 23, marginBottom: 5 }, guide: { flexDirection: "row", gap: 13, borderWidth: 1, borderRadius: 20, padding: 15 }, icon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 5 }, guideTitle: { fontSize: 16, fontWeight: "900" }, guideBody: { fontSize: 13, lineHeight: 19 }, note: { borderRadius: 20, padding: 16, gap: 5, marginTop: 4 }, noteTitle: { fontSize: 15, fontWeight: "900" }, noteBody: { fontSize: 13, lineHeight: 19 } });
