import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import * as LocalAuthentication from "expo-local-authentication";
import { AethelButton, BrandMark } from "@/components/aethel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAuth } from "@/hooks/use-auth";
import { useGoogleSignIn } from "@/lib/firebase-auth";
import { getBiometricEnabled, getConsent, saveConsent, setBiometricEnabled } from "@/lib/onboarding";
import { Fonts } from "@/constants/theme";

export default function EntryScreen() {
  const colors = useColors();
  const router = useRouter();
  const { isAuthenticated } = useAuth();
  const google = useGoogleSignIn();
  const [consent, setConsent] = useState(false);
  const [termsChecked, setTermsChecked] = useState(false);
  const [privacyChecked, setPrivacyChecked] = useState(false);
  const [biometricPrompt, setBiometricPrompt] = useState(false);
  const [ready, setReady] = useState(false);

  useEffect(() => { void Promise.all([getConsent(), getBiometricEnabled()]).then(([savedConsent, biometricEnabled]) => { setConsent(Boolean(savedConsent)); setBiometricPrompt(Boolean(savedConsent && !biometricEnabled)); setReady(true); }); }, []);
  useEffect(() => { if (isAuthenticated) router.replace("/(tabs)"); }, [isAuthenticated, router]);

  const acceptConsent = async () => { if (!termsChecked || !privacyChecked) return; await saveConsent(); setConsent(true); setBiometricPrompt(true); };
  const setupBiometric = async () => {
    const hardware = await LocalAuthentication.hasHardwareAsync();
    const enrolled = hardware && await LocalAuthentication.isEnrolledAsync();
    if (!enrolled) { Alert.alert("Biometrics not ready", "Enroll Face ID or a fingerprint in your device settings first. You can continue without it."); setBiometricPrompt(false); return; }
    const result = await LocalAuthentication.authenticateAsync({ promptMessage: "Protect your Aethel vault", disableDeviceFallback: false });
    if (result.success) { await setBiometricEnabled(true); setBiometricPrompt(false); }
  };

  if (!ready) return <ScreenContainer><View style={styles.loading}><BrandMark /><Text style={[styles.loadingText, { color: colors.muted }]}>Preparing your private space</Text></View></ScreenContainer>;
  return <ScreenContainer><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
    <View style={styles.topbar}><BrandMark /><View style={[styles.status, { backgroundColor: colors.accentSoft }]}><View style={[styles.statusDot, { backgroundColor: colors.success }]} /><Text style={[styles.statusText, { color: colors.primary }]}>LOCAL FIRST</Text></View></View>
    <View style={[styles.hero, { backgroundColor: colors.primary }]}><View style={styles.heroLine} /><Text style={styles.kicker}>A PRIVATE DAILY SYSTEM</Text><Text style={[styles.title, { fontFamily: Fonts.display }]}>A calmer place for the things that matter.</Text><Text style={styles.subtitle}>Keep your secrets, due dates, and attention together without handing over the keys.</Text><View style={styles.signalRow}><Signal icon="shield" label="Encrypted" /><Signal icon="cloud-off" label="Offline ready" /><Signal icon="fingerprint" label="You choose biometrics" /></View></View>
    <View style={styles.intro}><Text style={[styles.sectionTitle, { color: colors.foreground, fontFamily: Fonts.display }]}>Welcome to Aethel</Text><Text style={[styles.sectionBody, { color: colors.muted }]}>Start with a private local workspace. Google sign-in is optional and only used when you choose to sync.</Text></View>
    <View style={styles.featureGrid}><Feature icon="vpn-key" title="Vault" detail="Protect passwords, cards, and notes." /><Feature icon="event-note" title="Bills" detail="See what needs attention next." /><Feature icon="timer" title="Focus" detail="Make room for deep work." /></View>
    <View style={[styles.authCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.authTitle, { color: colors.foreground }]}>Your workspace is ready when you are</Text><Text style={[styles.authCopy, { color: colors.muted }]}>Accept the documents below, then continue locally or connect Google for sync.</Text><AethelButton onPress={() => void google.signIn()} icon="login">Continue with Google</AethelButton><Pressable onPress={() => router.replace("/(tabs)")} style={styles.offlineButton}><Text style={[styles.offlineText, { color: colors.primary }]}>Explore offline first</Text></Pressable></View>
    <View style={styles.legalRow}><Text style={[styles.legal, { color: colors.muted }]}>You choose what you accept. Read the</Text><Pressable onPress={() => router.push("/legal/terms")}><Text style={[styles.legalLink, { color: colors.primary }]}>Terms</Text></Pressable><Text style={[styles.legal, { color: colors.muted }]}>and</Text><Pressable onPress={() => router.push("/legal/privacy")}><Text style={[styles.legalLink, { color: colors.primary }]}>Privacy Policy</Text></Pressable><Text style={[styles.legal, { color: colors.muted }]}>before continuing.</Text></View>
  </ScrollView><Modal visible={!consent} transparent animationType="none"><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.surface }]}><Text style={[styles.modalKicker, { color: colors.primary }]}>ONE CLEAR CHOICE</Text><Text style={[styles.modalTitle, { color: colors.foreground, fontFamily: Fonts.display }]}>Before we open the door</Text><Text style={[styles.modalBody, { color: colors.muted }]}>Please read and actively accept both documents. Nothing is recorded until you press Continue.</Text><ConsentRow label="I agree to the Terms of Service" checked={termsChecked} onPress={() => setTermsChecked(!termsChecked)} onLink={() => router.push("/legal/terms")} /><ConsentRow label="I acknowledge the Privacy Policy" checked={privacyChecked} onPress={() => setPrivacyChecked(!privacyChecked)} onLink={() => router.push("/legal/privacy")} /><AethelButton onPress={() => void acceptConsent()} icon="check-circle">Continue</AethelButton></View></View></Modal><Modal visible={consent && biometricPrompt} transparent animationType="none"><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.surface }]}><Text style={[styles.modalKicker, { color: colors.primary }]}>OPTIONAL DEVICE PROTECTION</Text><Text style={[styles.modalTitle, { color: colors.foreground, fontFamily: Fonts.display }]}>Set up biometric unlock</Text><Text style={[styles.modalBody, { color: colors.muted }]}>Aethel has not enabled Face ID or fingerprint access yet. We will ask your device to confirm enrollment now.</Text><AethelButton onPress={() => void setupBiometric()} icon="fingerprint">Enable on this device</AethelButton><Pressable onPress={() => setBiometricPrompt(false)} style={styles.offlineButton}><Text style={[styles.offlineText, { color: colors.primary }]}>Skip for now</Text></Pressable></View></View></Modal></ScreenContainer>;
}

function Signal({ icon, label }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string }) { return <View style={styles.signal}><MaterialIcons name={icon} size={15} color="#F4E8D8" /><Text style={styles.signalText}>{label}</Text></View>; }
function Feature({ icon, title, detail }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; detail: string }) { const colors = useColors(); return <View style={[styles.feature, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.featureIcon, { backgroundColor: colors.accentSoft }]}><MaterialIcons name={icon} size={19} color={colors.primary} /></View><Text style={[styles.featureTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.featureDetail, { color: colors.muted }]}>{detail}</Text></View>; }
function ConsentRow({ label, checked, onPress, onLink }: { label: string; checked: boolean; onPress: () => void; onLink: () => void }) { const colors = useColors(); return <View style={styles.consentRow}><Pressable onPress={onPress} style={[styles.checkbox, { borderColor: checked ? colors.primary : colors.border, backgroundColor: checked ? colors.primary : colors.background }]}>{checked && <MaterialIcons name="check" size={16} color="#FFFFFF" />}</Pressable><Pressable onPress={onLink} style={styles.consentCopy}><Text style={[styles.consentText, { color: colors.foreground }]}>{label}</Text><Text style={[styles.readText, { color: colors.primary }]}>Read document</Text></Pressable></View>; }

const styles = StyleSheet.create({ loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 16 }, loadingText: { fontSize: 14 }, page: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 34, gap: 20 }, topbar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, status: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 99 }, statusDot: { width: 6, height: 6, borderRadius: 99 }, statusText: { fontSize: 9, fontWeight: "900", letterSpacing: 1 }, hero: { minHeight: 355, borderRadius: 28, padding: 23, overflow: "hidden", justifyContent: "flex-end", gap: 13 }, heroLine: { position: "absolute", width: 190, height: 190, borderRadius: 95, borderWidth: 1, borderColor: "#F4E8D844", right: -55, top: -52 }, kicker: { color: "#F4E8D8", fontSize: 10, fontWeight: "900", letterSpacing: 1.7 }, title: { color: "#FFFFFF", fontSize: 39, lineHeight: 42, fontWeight: "700" }, subtitle: { color: "#F7F0E8", fontSize: 15, lineHeight: 22, maxWidth: 330 }, signalRow: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 7 }, signal: { flexDirection: "row", alignItems: "center", gap: 5 }, signalText: { color: "#F4E8D8", fontSize: 11, fontWeight: "700" }, intro: { gap: 5 }, sectionTitle: { fontSize: 25, lineHeight: 30, fontWeight: "700" }, sectionBody: { fontSize: 15, lineHeight: 22 }, featureGrid: { flexDirection: "row", gap: 9 }, feature: { flex: 1, minHeight: 139, borderRadius: 16, borderWidth: 1, padding: 12, gap: 7 }, featureIcon: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", marginBottom: 4 }, featureTitle: { fontSize: 15, fontWeight: "900" }, featureDetail: { fontSize: 11, lineHeight: 15 }, authCard: { borderWidth: 1, borderRadius: 20, padding: 18, gap: 10 }, authTitle: { fontSize: 19, fontWeight: "900" }, authCopy: { fontSize: 13, lineHeight: 19, marginBottom: 4 }, offlineButton: { alignItems: "center", minHeight: 38, justifyContent: "center" }, offlineText: { fontSize: 14, fontWeight: "900" }, legalRow: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 3, paddingHorizontal: 8 }, legal: { fontSize: 11, lineHeight: 16 }, legalLink: { fontSize: 11, lineHeight: 16, fontWeight: "900" }, modalBackdrop: { flex: 1, justifyContent: "center", padding: 20, backgroundColor: "rgba(16,35,33,0.58)" }, modal: { borderRadius: 22, padding: 21, gap: 14 }, modalKicker: { fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, modalTitle: { fontSize: 29, lineHeight: 33, fontWeight: "700" }, modalBody: { fontSize: 14, lineHeight: 21 }, consentRow: { flexDirection: "row", alignItems: "center", gap: 11 }, checkbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1, alignItems: "center", justifyContent: "center" }, consentCopy: { flex: 1, gap: 3 }, consentText: { fontSize: 14, fontWeight: "800" }, readText: { fontSize: 12, fontWeight: "700" } });
