import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import React, { useEffect } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { AethelButton, Pill, SectionHeading } from "@/components/aethel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAethel } from "@/lib/aethel-store";
import { formatFocusTime } from "@/lib/aethel-utils";

const quickOptions = [15, 25, 45, 60];

export default function FocusScreen() {
  const colors = useColors();
  const { focus, startFocus, tickFocus, endFocus } = useAethel();
  useEffect(() => { if (!focus.active) return; const interval = setInterval(tickFocus, 1000); return () => clearInterval(interval); }, [focus.active, tickFocus]);
  return <ScreenContainer><View style={styles.page}><View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.info }]}>MAKE SPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Focus</Text></View><View style={[styles.statusDot, { backgroundColor: focus.active ? colors.success : colors.border }]} /></View><Text style={[styles.subtitle, { color: colors.muted }]}>One protected block is often enough to move the day forward.</Text><View style={[styles.timerCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pill label={focus.active ? "LOCK ACTIVE" : "READY WHEN YOU ARE"} color={focus.active ? colors.success : colors.info} icon={focus.active ? "lock" : "schedule"} /><Text style={[styles.timer, { color: colors.foreground }]}>{formatFocusTime(focus.remainingSeconds)}</Text><Text style={[styles.timerLabel, { color: colors.muted }]}>{focus.active ? focus.label : "Deep work"}</Text><View style={styles.timerActions}>{focus.active ? <AethelButton variant="secondary" onPress={endFocus} icon="stop">End session</AethelButton> : <AethelButton onPress={() => startFocus(25)} icon="play-arrow">Start 25 min</AethelButton>}</View></View><SectionHeading eyebrow="Quick start" title="Choose a window" /><View style={styles.optionGrid}>{quickOptions.map((minutesOption) => <Pressable key={minutesOption} onPress={() => startFocus(minutesOption)} style={({ pressed }) => [styles.option, { borderColor: colors.border, backgroundColor: colors.surface }, pressed && { borderColor: colors.primary, opacity: 0.8 }]}><Text style={[styles.optionValue, { color: colors.foreground }]}>{minutesOption}</Text><Text style={[styles.optionUnit, { color: colors.muted }]}>min</Text></Pressable>)}</View><View style={[styles.infoCard, { backgroundColor: colors.inkSoft }]}><MaterialIcons name="shield" size={22} color={colors.primary} /><View style={styles.infoCopy}><Text style={[styles.infoTitle, { color: colors.foreground }]}>What gets protected?</Text><Text style={[styles.infoBody, { color: colors.muted }]}>Aethel’s focus layer is designed to keep distracting apps out of reach while you work.</Text></View></View><Text style={[styles.permissionNote, { color: colors.muted }]}>App blocking permissions are optional and will be requested only when you choose to turn them on.</Text></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 20, paddingTop: 20, gap: 20 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, eyebrow: { fontSize: 11, letterSpacing: 1.3, fontWeight: "800", marginBottom: 5 }, title: { fontSize: 34, lineHeight: 38, fontWeight: "800", letterSpacing: -1 }, subtitle: { fontSize: 15, lineHeight: 21, marginTop: -12 }, statusDot: { width: 11, height: 11, borderRadius: 11 }, timerCard: { borderWidth: 1, borderRadius: 25, alignItems: "center", paddingVertical: 25, gap: 10 }, timer: { fontSize: 68, lineHeight: 77, fontWeight: "300", letterSpacing: -3, fontVariant: ["tabular-nums"] }, timerLabel: { fontSize: 15, fontWeight: "700" }, timerActions: { marginTop: 7 }, optionGrid: { flexDirection: "row", gap: 9 }, option: { flex: 1, minHeight: 82, borderRadius: 17, borderWidth: 1, alignItems: "center", justifyContent: "center" }, optionValue: { fontSize: 23, fontWeight: "800" }, optionUnit: { fontSize: 12, fontWeight: "700", marginTop: 2 }, infoCard: { borderRadius: 18, padding: 16, flexDirection: "row", gap: 12 }, infoCopy: { flex: 1, gap: 4 }, infoTitle: { fontSize: 15, fontWeight: "800" }, infoBody: { fontSize: 13, lineHeight: 19 }, permissionNote: { fontSize: 12, lineHeight: 18, textAlign: "center", paddingHorizontal: 15 }, });
