import * as Clipboard from "expo-clipboard";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import React, { useMemo, useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";

import { AethelButton } from "@/components/aethel-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAethel, type VaultItem, type VaultKind } from "@/lib/aethel-store";
import { useAethelPreferences } from "@/lib/aethel-preferences";
import { authenticateBiometric } from "@/lib/aethel-crypto";

const filters: ("all" | VaultKind)[] = ["all", "password", "card", "note"];
const filterLabels = { all: "All", password: "Passwords", card: "Cards", note: "Notes" };

export default function VaultScreen() {
  const colors = useColors();
  const router = useRouter();
  const { vault, addVaultItem, removeVaultItem } = useAethel();
  const { biometricEnabled } = useAethelPreferences();
  const [filter, setFilter] = useState<(typeof filters)[number]>("all");
  const [revealed, setRevealed] = useState<string | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  const [title, setTitle] = useState("");
  const [username, setUsername] = useState("");
  const [secret, setSecret] = useState("");
  const [kind, setKind] = useState<VaultKind>("password");
  const data = useMemo(() => filter === "all" ? vault : vault.filter((item) => item.kind === filter), [filter, vault]);
  const handleAdd = () => { if (!title.trim() || !secret.trim()) return; addVaultItem({ title: title.trim(), username: username.trim(), secret: secret.trim(), kind }); setTitle(""); setUsername(""); setSecret(""); setShowAdd(false); };
  const requireBiometric = async (prompt: string) => { if (!biometricEnabled) { Alert.alert("Turn on biometric unlock first", "Aethel never assumes you want biometric protection. Enable it in Settings before revealing a secret.", [{ text: "Not now" }, { text: "Open Settings", onPress: () => router.push("/settings") }]); return false; } return authenticateBiometric(prompt); };
  const handleCopy = async (item: VaultItem) => { if (!item.secret) return; const approved = await requireBiometric("Copy protected secret"); if (!approved) { Alert.alert("Biometric check required", "Aethel did not reveal or copy this protected value."); return; } await Clipboard.setStringAsync(item.secret); Alert.alert("Copied securely", "The protected value was copied after biometric approval."); };
  const handleReveal = async (id: string) => { if (revealed === id) { setRevealed(null); return; } const approved = await requireBiometric("Reveal protected secret"); if (approved) setRevealed(id); else Alert.alert("Biometric check required", "Aethel did not reveal this protected value."); };
  const handleDelete = (item: VaultItem) => Alert.alert("Delete item?", `${item.title} will be removed from this device.`, [{ text: "Keep" }, { text: "Delete", style: "destructive", onPress: () => removeVaultItem(item.id) }]);
  return <ScreenContainer><View style={styles.page}><View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>PRIVATE BY DEFAULT</Text><Text style={[styles.title, { color: colors.foreground }]}>Vault</Text></View><Pressable onPress={() => setShowAdd(true)} style={[styles.addButton, { backgroundColor: colors.primary }]} accessibilityLabel="Add vault item"><MaterialIcons name="add" color="#FFFFFF" size={22} /></Pressable></View><Text style={[styles.subtitle, { color: colors.muted }]}>Your labels stay searchable. Your secrets stay yours.</Text><View style={styles.filters}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, { borderColor: filter === item ? colors.primary : colors.border, backgroundColor: filter === item ? `${colors.primary}18` : colors.surface }]}><Text style={[styles.filterText, { color: filter === item ? colors.primary : colors.muted }]}>{filterLabels[item]}</Text></Pressable>)}</View><FlatList data={data} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} renderItem={({ item }) => <VaultCard item={item} isRevealed={revealed === item.id} onReveal={() => handleReveal(item.id)} onCopy={() => handleCopy(item)} onDelete={() => handleDelete(item)} />} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="lock-open" size={26} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Your vault is ready</Text><Text style={[styles.emptyBody, { color: colors.muted }]}>Add your first protected item. Secrets are stored locally on this device.</Text><AethelButton onPress={() => setShowAdd(true)} icon="add">Add an item</AethelButton></View>} /><AddVaultModal visible={showAdd} kind={kind} title={title} username={username} secret={secret} onClose={() => setShowAdd(false)} onKind={setKind} onTitle={setTitle} onUsername={setUsername} onSecret={setSecret} onSave={handleAdd} /></View></ScreenContainer>;
}

function VaultCard({ item, isRevealed, onReveal, onCopy, onDelete }: { item: VaultItem; isRevealed: boolean; onReveal: () => void; onCopy: () => void; onDelete: () => void }) { const colors = useColors(); const icon = item.kind === "card" ? "credit-card" : item.kind === "note" ? "description" : "key"; const kindLabel = item.kind === "password" ? "PASSWORD" : item.kind.toUpperCase(); return <View style={[styles.vaultCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><View style={[styles.vaultIcon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name={icon} size={21} color={colors.primary} /></View><View style={styles.cardHeading}><Text style={[styles.cardLabel, { color: colors.muted }]}>{kindLabel}</Text><Text style={[styles.cardTitle, { color: colors.foreground }]}>{item.title}</Text></View><Pressable onPress={onDelete} hitSlop={10}><MaterialIcons name="more-horiz" size={22} color={colors.muted} /></Pressable></View><Text style={[styles.username, { color: colors.muted }]}>{item.username || "Private note"}</Text><View style={[styles.secretRow, { backgroundColor: colors.inkSoft }]}><Text selectable={isRevealed} style={[styles.secret, { color: colors.foreground }]}>{isRevealed ? item.secret || item.note : "••••••••••••••"}</Text><Pressable onPress={onReveal} style={styles.revealButton}><MaterialIcons name={isRevealed ? "visibility-off" : "visibility"} size={19} color={colors.primary} /><Text style={[styles.revealText, { color: colors.primary }]}>{isRevealed ? "Hide" : "Reveal"}</Text></Pressable></View>{isRevealed && <Pressable onPress={onCopy} style={styles.copyRow}><MaterialIcons name="content-copy" size={16} color={colors.primary} /><Text style={[styles.copyText, { color: colors.primary }]}>Copy secret</Text><Text style={[styles.bioText, { color: colors.muted }]}>Biometric check on each reveal</Text></Pressable>}</View>; }

function AddVaultModal({ visible, kind, title, username, secret, onClose, onKind, onTitle, onUsername, onSecret, onSave }: { visible: boolean; kind: VaultKind; title: string; username: string; secret: string; onClose: () => void; onKind: (kind: VaultKind) => void; onTitle: (value: string) => void; onUsername: (value: string) => void; onSecret: (value: string) => void; onSave: () => void }) { const colors = useColors(); return <Modal visible={visible} transparent animationType="none" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.surface }]}><View style={styles.modalHeader}><Text style={[styles.modalTitle, { color: colors.foreground }]}>New vault item</Text><Pressable onPress={onClose}><MaterialIcons name="close" size={22} color={colors.muted} /></Pressable></View><Text style={[styles.modalHint, { color: colors.muted }]}>Only the title is designed to be searchable. Keep sensitive details on-device.</Text><View style={styles.kindRow}>{(["password", "card", "note"] as VaultKind[]).map((value) => <Pressable key={value} onPress={() => onKind(value)} style={[styles.kindChip, { borderColor: kind === value ? colors.primary : colors.border, backgroundColor: kind === value ? `${colors.primary}18` : colors.background }]}><Text style={[styles.kindText, { color: kind === value ? colors.primary : colors.muted }]}>{filterLabels[value]}</Text></Pressable>)}</View><TextInput value={title} onChangeText={onTitle} placeholder="Title" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /><TextInput value={username} onChangeText={onUsername} placeholder={kind === "note" ? "Label (optional)" : "Username or last four"} placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /><TextInput value={secret} onChangeText={onSecret} placeholder={kind === "note" ? "Private note" : "Secret value"} placeholderTextColor={colors.muted} secureTextEntry={kind !== "note"} multiline={kind === "note"} style={[styles.input, kind === "note" && styles.noteInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /><AethelButton onPress={onSave} icon="lock">Save privately</AethelButton></View></View></Modal>; }

const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 20, paddingTop: 20 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, eyebrow: { fontSize: 11, letterSpacing: 1.3, fontWeight: "800", marginBottom: 5 }, title: { fontSize: 34, lineHeight: 38, fontWeight: "800", letterSpacing: -1 }, subtitle: { fontSize: 15, lineHeight: 21, marginTop: 6, marginBottom: 21 }, addButton: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center" }, filters: { flexDirection: "row", gap: 7, marginBottom: 14 }, filter: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 99, borderWidth: 1 }, filterText: { fontSize: 12, fontWeight: "800" }, list: { gap: 12, paddingBottom: 28 }, vaultCard: { borderRadius: 20, borderWidth: 1, padding: 16, gap: 13 }, cardTop: { flexDirection: "row", alignItems: "center" }, vaultIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cardHeading: { flex: 1, marginLeft: 11 }, cardLabel: { fontSize: 10, letterSpacing: 1.2, fontWeight: "800", marginBottom: 3 }, cardTitle: { fontSize: 17, fontWeight: "800" }, username: { fontSize: 14, marginLeft: 53 }, secretRow: { minHeight: 48, borderRadius: 13, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 }, secret: { flex: 1, fontFamily: "monospace", fontSize: 14 }, revealButton: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 8 }, revealText: { fontSize: 12, fontWeight: "800" }, copyRow: { flexDirection: "row", alignItems: "center", gap: 7 }, copyText: { fontSize: 13, fontWeight: "800" }, bioText: { fontSize: 11, marginLeft: "auto" }, empty: { borderRadius: 20, borderWidth: 1, alignItems: "center", gap: 10, padding: 25 }, emptyTitle: { fontSize: 18, fontWeight: "800" }, emptyBody: { fontSize: 14, lineHeight: 20, textAlign: "center", marginBottom: 6 }, modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.42)" }, modal: { borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, gap: 13 }, modalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, modalTitle: { fontSize: 22, fontWeight: "800" }, modalHint: { fontSize: 13, lineHeight: 18 }, kindRow: { flexDirection: "row", gap: 7 }, kindChip: { flex: 1, borderRadius: 12, borderWidth: 1, paddingVertical: 10, alignItems: "center" }, kindText: { fontSize: 12, fontWeight: "800" }, input: { minHeight: 48, borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, fontSize: 15 }, noteInput: { minHeight: 86, textAlignVertical: "top", paddingTop: 13 } });
